#makefile for the client side interface

#calling the gcc compiler to build the code
all: dfserver.c
	gcc dfserver.c -o dfserver

#clean up the executable created
clean:
	rm -rf dfserver .foo.txt.1 .foo.txt.2 .foo.txt.3 .foo.txt.4
